### ISSUE TITLE
localize state

### ISSUE THREAD

**Issue by tolitius** [shvetsm/funcade#1]
first off, thanks for the library, it's really useful

## suggestion

how about instead of having `funcade.state` have something like:

```clojure
(defn wake-token-maker [token-name config]
  (let [token-maker (...)]
  ...
    {:next-token #(-> @token-maker token-name :access-token)
     :stop (partial stop-token-channel! stop-channel)}))
```

that would do all the internal things take care of the channels (since it's an internal implementation detail), etc. and will return two functions:

```
{:next-token ;; a function that would return next/current token
 :stop       ;; a function that would stop token maker}
```

then the client of this library could:

```clojure
(def token-maker (funcade/wake-token-maker :orion {...}))
```

and whenever the token is needed:

```
(token-maker/next-token)
```
```

**Comment by shvetsm** [comment]
fixed 9e3d1c6
